[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/tools/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200 